name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: |
          npm ci
          cd client && npm ci

      - name: Run backend tests
        run: npm test

      - name: Run frontend tests
        run: cd client && npm test

      - name: Build frontend
        run: cd client && npm run build
